[preview]
max_width = 800  # 最大预览宽度
max_height = 600 # 最大预览高度

# 文本文件预览
[preview.text]
command = "bat --color=always --style=numbers $file"
cache = false  # 文本文件不缓存

# 视频预览（使用 ffmpegthumbnailer）
[preview.video]
command = "ffmpegthumbnailer -i $file -o - -s 600"
cache = true   # 视频缩略图缓存

# PDF 预览
[preview.pdf]
command = "pdftoppm -jpeg -f 1 -l 1 $file -"
cache = true
