[mgr]
show_hidden = true  # 默认显示隐藏文件
sort_by = "natural" # 按修改时间排序：name/size/modified/created

[preview]
max_width = 800      # 预览最大宽度
max_height = 600     # 预览最大高度

[opener]
vlc-play = [
 { run ='vlc "$@"', orphan = true, for = "unix" }
]
epubRead = [
 { run ='foliate "$@"', orphan = true, for = "unix" }
]
PDFReader = [
 { run ='zathura "$@"', orphan = true, for = "unix"}
]
imageReader = [
 {run ='imv "$@"', orphan = true, for = "unix"}
]

[open]
rules = [
  #video player 
  { mime = "video/*", use = "vlc-play" },
  { name = "*.mp4", use = "vlc-play" },
  { name = "*.mkv", use = "vlc-play"},
  #audio player
  { name = "*.aac", use = "vlc-play"},
  #e-book reader
  { name = "*.epub", use = "epubRead" },
  #PDF Reader
  { name = "*.pdf", use = "PDFReader"},
  #image Reader
  { name = "*.jpeg", use = "imageReader"},
  { name = "*.png", use = "imageReader"}
    
]
