// Virtual module generated by vite-plugin-blog
// This file imports the processed blog data from our Vite plugin
import { getAllPosts, getPostBySlug, getPostsByTag as getPostsByTagFromPlugin } from 'virtual:blog-data';

// Export the blog data for use in components
export const posts = getAllPosts();
export const getPost = getPostBySlug;
export const getPostsByTag = getPostsByTagFromPlugin;

// Helper functions for components
export const getLatestPosts = (limit = 5) => posts.slice(0, limit);
export const getPostsCount = () => posts.length;
export const getAllTags = () => {
  const tags = new Set();
  posts.forEach(post => {
    post.tags.forEach(tag => tags.add(tag));
  });
  return Array.from(tags);
};
